allowBuilds:
  '@parcel/watcher': true
  core-js: true
  cypress: true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
minimumReleaseAge: 0
minimumReleaseAgeExclude:
  - '@angular-devkit/architect@0.2102.13'
  - '@angular-devkit/core@21.2.13'
  - '@angular-devkit/schematics@21.2.13'
  - '@angular/build@21.2.13'
  - '@angular/cli@21.2.13'
  - '@schematics/angular@21.2.13'
  - '@angular-devkit/architect@0.2200.1'
  - '@angular-devkit/core@22.0.1'
  - '@angular-devkit/schematics@22.0.1'
  - '@angular/cli@22.0.1'
  - '@schematics/angular@22.0.1'
  - '@angular/animations@22.0.1'
  - '@angular/build@22.0.1'
  - '@angular/common@22.0.1'
  - '@angular/compiler-cli@22.0.1'
  - '@angular/compiler@22.0.1'
  - '@angular/core@22.0.1'
  - '@angular/forms@22.0.1'
  - '@angular/language-service@22.0.1'
  - '@angular/localize@22.0.1'
  - '@angular/platform-browser-dynamic@22.0.1'
  - '@angular/platform-browser@22.0.1'
  - '@angular/router@22.0.1'
